### ISSUE TITLE
# AttributeError: 'Window' object has no attribute 'get_limitation' (incompatible with pyvlx >= 0.2.33)

### ISSUE THREAD

**Issue by brunoz78** [pawlizio/my_velux#79]
## Description

`VeluxWindow.async_update_limitation()` calls `node.get_limitation()`, which no longer
exists in pyvlx 0.2.33 and later. Every coordinator refresh for window entities fails
with an uncaught `AttributeError`.

The existing `except PyVLXException` does not catch this, so the error surfaces as a
full traceback from the DataUpdateCoordinator rather than the intended log message.
This is a different failure path from #77, where the `except` block does catch a
genuine `PyVLXException` and logs from line 235.

Only motorised roof windows are affected — roller shutters never enter this code path.

## Environment

| | |
|---|---|
| my_velux | 2.9.23 |
| Home Assistant Core | 2026.7.4 |
| Installed pyvlx | 0.2.36 (pulled in by HA Core) |
| Devices | 2 × VELUX roof window (KLF 200) |

## Traceback

```
ERROR (MainThread) [custom_components.velux] Unexpected error fetching 53:27:43:26:19:06:00:2f data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 435, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/velux/cover.py", line 231, in async_update_limitation
    limitation: GetLimitation = await self.node.get_limitation()
AttributeError: 'Window' object has no attribute 'get_limitation'. Did you mean: 'get_limitation_max'?
```

## Root cause

pyvlx replaced the single combined call with two separate ones. Verified by inspecting
the sdists from PyPI:

| pyvlx | Released | `get_limitation()` | `get_limitation_min()` / `get_limitation_max()` |
|---|---|---|---|
| 0.2.30 | 2026-02-16 | yes | no |
| 0.2.31 | 2026-03-18 | yes | yes |
| 0.2.32 | 2026-03-19 | yes | yes |
| **0.2.33** | 2026-04-09 | **removed** | yes |
| 0.2.36 | 2026-06-24 | no | yes |

Note that `manifest.json` currently pins `pyvlx==0.2.33` — the very release in which
`OpeningDevice.get_limitation()` was removed. The component is therefore incompatible
with its own declared requirement, independent of any version conflict with HA Core
(which requires `pyvlx==0.2.36`).

The return type also changed: `get_limitation_min()` and `get_limitation_max()` each
return a `Position` object, so the value is read from `.position_percent` instead of
`.min_value` / `.max_value`. The `GetLimitation` class itself still exists (it gained a
`limitation_type` argument), so the existing import remains valid.

## Proposed fix

Backwards compatible — works with both old and new pyvlx releases:

```python
    async def async_update_limitation(self):
        """Get the updated status of the cover (limitations only)."""
        try:
            if hasattr(self.node, "get_limitation_max"):
                # pyvlx >= 0.2.31: separate calls, each returning a Position
                self._extra_attr_limitation_min = (
                    await self.node.get_limitation_min()
                ).position_percent
                self._extra_attr_limitation_max = (
                    await self.node.get_limitation_max()
                ).position_percent
            else:
                # pyvlx <= 0.2.30: combined call
                limitation: GetLimitation = await self.node.get_limitation()
                self._extra_attr_limitation_min = limitation.min_value
                self._extra_attr_limitation_max = limitation.max_value
        except PyVLXException:
            LOGGER.error("Error fetch limitation data for cover %s", self.name)
```

Aligning `manifest.json` with HA Core (`pyvlx==0.2.36`) would additionally avoid the
conflicting requirement, since both integrations share the `velux` domain and only one
version of the library can be installed.

### Verified

I applied the patch above on my installation (2 roof windows, pyvlx 0.2.36). The
`AttributeError` is gone and both entities now populate the attributes correctly on the
first coordinator run:

```
cover.buro_dachfesnter           limitation_min: 0   limitation_max: 100
cover.treppenhaus_dachfenster_2  limitation_min: 0   limitation_max: 100
```

I am happy to open a PR if that helps.
